# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Elasticommerce Search Service
  description: The Elasticommerce Search Service API
  version: "1.0.0"
# the domain of the service
host: api.example.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /dev
produces:
  - application/json
paths:
  /searchword:
    get:
      summary: 検索ワードに対する売上データをJSONで取得します。
      description: 開始日と終了日を指定してその期間の売上データを取得します。検索ワードを直接指定しての検索も可能です
      parameters:
        - name: searchword
          in: query
          description: 検索ワード
          required: false
          type: string
        - name: start_date
          in: query
          description: 開始日
          required: true
          type: number
        - name: end_date
          in: query
          description: 終了日.
          required: true
          type: number
      tags:
        - Searchword
      responses:
        200:
          description: 売上データのJSON
          schema:
            type: array
            items:
              $ref: '#/definitions/searchword'
    post:
      summary: 検索ワードに対する売上データを登録します
      description: |
        検索ワードに対する商品情報と合計金額を登録します
      parameters:
        - name: productinfo
          in: body
          description: 商品情報
          required: true
          schema:
            $ref: '#/definitions/searchword'
      tags:
        - Searchword
      responses:
        200:
          description: 空のJSONが返ってくる
        400:
          description: ErrorのJSONが返ってくる
definitions:
  productinfo:
    type: object
    properties:
      product_id:
        type: string
        description: 商品ID
      count:
        type: string
        description: 購入数.
  searchword:
    type: object
    properties:
      searchword:
        type: string
        description: 検索ワード
      productinfo:
        type: array
        description: 購入情報.
        items:
          $ref: '#/definitions/productinfo'
      totalvalue:
        type: number
        description: 売上金額.

